apiVersion: apps/v1
kind: Deployment
metadata:
  name: universal-verifier-front-deployment
  labels:
    app: universal-verifier-front
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: universal-verifier-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: universal-verifier-front
    spec:
      containers:
        - image: k8scrvidchaindev.azurecr.io/universal-verifier-front:latest
          imagePullPolicy: "Always"
          name: universal-verifier-front
          ports:
            - containerPort: 3000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: universal-verifier-front-service
  labels:
    app: universal-verifier-front
spec:
  type: ClusterIP
  ports:
    - name: "9071"
      port: 9071
      targetPort: 3000
  selector:
    app: universal-verifier-front

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: universal-verifier-front-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - dev-verifier.vidchain.net
      secretName: wildcard-vidchain-net
  rules:
    - host: dev-verifier.vidchain.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: universal-verifier-front-service
                port:
                  number: 9071
          - path: /callback(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: universal-verifier-front-service
                port:
                  number: 9071